Created UpdateHearingParticipants endpoint along with an UpdateHearin…
hmcts/vh-video-api pull request #393
Opened 2021-06-23 10:58 UTC by AWildBugAppeared

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/VIH-7766

### Change description ###
Created a new endpoint and command which is responsible for updating a conference's participants.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2021-06-28 13:49 UTC, alberto-hortiguela requested changes
Comments for review

2021-06-28 14:09 UTC, AWildBugAppeared commented on VideoApi/VideoApi.IntegrationTests/Database/Commands/UpdateConferenceParticipantsCommandTests.cs
> +        public async Task Should_remove_participants_from_conference()
Spoken with Alberto. This test is required.

2021-06-30 13:51 UTC, omio-ma commented
/azp run

2021-06-30 15:28 UTC, alberto-hortiguela approved these changes
LGTM

2021-06-30 16:02 UTC, merged